### PR TITLE
Fix Python 3 compatibility

### PR DESCRIPTION
**Pull request by crgwbr**
Fixes issue #56.

### CODE REVIEW

**Comment by froi** [comment]
Any chance of getting this merged?

**Comment by dlapiduz** [comment]
Apologies for the super long delay. I've been out of github...

**Comment by sindrig** [comment]
Will you publish a new version to pypi?

**Comment by dlapiduz** [comment]
@sindrig oops, there was an issue with pypi and the CI system didn't notify me. It is up now.

**Comment by froi** [comment]
I'm a bit late with this but thank you @dlapiduz

**Pull request merged**
